### ISSUE TITLE
More number of layers

### ISSUE THREAD

**Issue by jfriend08** [jfriend08/DeepLearning#3]
According to [piazza](https://piazza.com/class/iicl1y199833v4?cid=34)
`you could play around with the different number of layers (going beyond 3 layers on CPU might be painful)`

**Comment by jfriend08** [comment]
also maybe we could try:
`different kernel sizes, pooling sizes, size of the hidden layer in the fully connected layer, different non-linearities (Tanh, sigmoid, ReLU) and Dropout (ignore if you don't know what this is)`

**Comment by jfriend08** [comment]
please refer [this](https://github.com/jfriend08/DeepLearning/blob/peter_dev/assignment1/3layermodel.lua) for 3LayerModel

**Comment by JoyceYao** [comment]
(1) Different kernel size: guassian 7 -> 15 ,  will lower the training correct rate by 0.01%
(2) Use image.laplacian() normalization to replace guassian1D, will serviously reduce the training correct rate
(3) Use ReLU, will lower training correct rate by 0.02%
